generate cycles as follows:  
input: arr, sarr = sorted(arr)  
construct cycles by chaining transpositions of (i arr[j])  
where:  
    i is i-th element in arr  
    j is the first non-used, non-stationary element arr[i]

In [ ]:
def minSwaps(arr):
    sarr = sorted(arr)
    length = len(sarr)
    visited = [o==s for o, s in zip(arr, sarr)]
    
    def find_index(value):
        for idx, elem in enumerate()
        
    
    for i in range(length):
        
        if visited[i]:
            continue
        
        
    

In [296]:
import itertools as it

In [297]:
import operator

In [184]:
ivs = list(enumerate([3,2,2,2,4,3,2]))

index_getter = operator.itemgetter(0)
value_getter = operator.itemgetter(1)

sivs = sorted(ivs, key=value_getter)

givs = dict((k, list(map(index_getter, g))) for k,g in it.groupby(sivs, key=value_getter))
givs

{2: [1, 2, 3, 6], 3: [0, 5], 4: [4]}

In [72]:
def f(val):
    for i, v in enumerate(original_vals):
        if v == val and available[i]: return i
    
def g(val):
    i = original_vals.index(val)
    while not available[i]:
        i = original_vals.index(val, i+1)
    return i

def h(val):
    i = 0
    while not (available[i] and original_vals[i]==val): i+=1
    return i

In [74]:
v = 8
print(f(v), g(v), h(v))
%timeit f(v)
%timeit g(v)
%timeit h(v)

16 16 16
791 ns ± 4.67 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
338 ns ± 2.78 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
1.31 µs ± 3.3 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [581]:
print(' '.join(map('{:2d}'.format, original_vals)))
print(' '.join(map('{:2d}'.format, sorted_vals)))
print(' '.join(map('{:2d}'.format, range(len(sorted_vals)))))

 3  2  2  2  4  3  2  1  6  5  7  4  6  6  5  4  8  4  4  1  1  3  2  2  2  2  6  2  2  3  5  8  4  2  2
 1  1  1  2  2  2  2  2  2  2  2  2  2  2  2  3  3  3  3  4  4  4  4  4  4  5  5  5  6  6  6  6  7  8  8
 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34


In [580]:

original_vals = [3,2,2,2,4,3,2,1,6,5,7,4,6,6,5,4,8,4,4,1,1,3,2,2,2,2,6,2,2,3,5,8,4,2,2]
original_idcs = list(range(len(original_vals)))

sorted_vals_idcs = sorted(zip(original_vals, original_idcs))
sorted_vals, sorted_idcs = zip(*sorted_vals_idcs)

available = [original_vals[i]!=sorted_vals[i] for i in range(len(original_vals))]

In [92]:
def min_swaps(sequence):
    original_vals = sequence
    length = len(original_vals)
    sorted_vals = sorted(original_vals)
    
    available = [original_vals[i]!=sorted_vals[i] for i in range(length)]

    def find(val):
        i = original_vals.index(val)
        while not available[i]:
            i = original_vals.index(val, i+1)
        return i

    permutations = []
    for i in range(length):

        if not available[i]: continue

        start_val = original_vals[i]
        target_val = sorted_vals[i]

        permutation = [i]

        while start_val != target_val:
            ni = find(target_val)
            available[ni] = False
            target_val = sorted_vals[ni]
            permutation.append(ni)

        available[i] = False
        permutations.append(permutation)
        
    return permutations

In [93]:
%timeit min_swaps([3,2,2,2,4,3,2,1,6,5,7,4,6,6,5,4,8,4,4,1,1,3,2,2,2,2,6,2,2,3,5,8,4,2,2])

29.7 µs ± 492 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
nai

In [182]:
%%cython
def min_swaps(sequence):
    original_vals = sequence
    length = len(original_vals)
    sorted_vals = sorted(original_vals)
    
    available = [original_vals[i]!=sorted_vals[i] for i in range(length)]

    #permutations = []
    swaps = 0
    for i in range(length):

        if not available[i]: continue

        start_val = original_vals[i]
        target_val = sorted_vals[i]

        #permutation = [i]

        while start_val != target_val:
            ni = original_vals.index(target_val)
            while not available[ni]:
                ni = original_vals.index(target_val, ni+1)
            available[ni] = False
            target_val = sorted_vals[ni]
            #permutation.append(ni)
            swaps += 1

        available[i] = False
        #permutations.append(permutation)
        
    return swaps #, permutations

In [157]:
nparr = np.random.randint(0, 10**8, 10000)
arr = list(nparr)

In [159]:
%timeit min_swaps(arr)

7.04 s ± 67.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [147]:
arr

array([0, 7, 6, 6, 7, 2, 8, 8, 4, 3, 3, 8, 0, 2, 0, 3, 7, 2, 1, 8, 3, 8,
       1, 2, 6, 1, 7, 4, 4, 4, 2, 5, 8, 4, 9, 2, 9, 2, 4, 5, 6, 4, 2, 5,
       1, 7, 0, 3, 4, 2, 4, 1, 3, 2, 2, 7, 8, 2, 5, 2, 9, 2, 1, 0, 4, 8,
       8, 6, 4, 6, 0, 2, 7, 6, 8, 6, 6, 4, 1, 6, 5, 5, 7, 2, 5, 9, 6, 6,
       7, 9, 2, 8, 9, 6, 5, 8, 7, 5, 5, 7])

In [275]:
%%cython
cpdef int min_swaps(list sequence):
    original_vals = sequence
    length = len(original_vals)
    sorted_vals = sorted(original_vals)
    
    cdef int i, ni, start_val, target_val
    available = [original_vals[i]!=sorted_vals[i] for i in range(length)]

    #permutations = []
    cdef int swaps = 0
    for i in range(length):

        if not available[i]: continue

        start_val = original_vals[i]
        target_val = sorted_vals[i]

        #permutation = [i]

        while start_val != target_val:
            ni = original_vals.index(target_val)
            while not available[ni]:
                ni = original_vals.index(target_val, ni+1)
            available[ni] = False
            target_val = sorted_vals[ni]
            #permutation.append(ni)
            swaps+=1

        available[i] = False
        #permutations.append(permutation)
        
    return swaps#, permutations

In [276]:
%timeit min_swaps(arr)

7.46 s ± 46.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [270]:
%%cython
import numpy as np
cimport numpy as np
DTYPE = np.int64
ctypedef np.int64_t DTYPE_t
cpdef int min_swaps(np.ndarray[DTYPE_t, ndim=1] sequence):
    cdef np.ndarray[DTYPE_t, ndim=1] original_vals = sequence
    cdef np.ndarray[DTYPE_t, ndim=1] sorted_vals = np.sort(original_vals)
    cdef np.ndarray[np.uint8_t, ndim=1, cast=True] available = original_vals!=sorted_vals

    #permutations = []
    cdef DTYPE_t start_val, target_val
    cdef int i, ni, swaps = 0
    for i in range(original_vals.shape[0]):

        if not available[i]: continue

        start_val = original_vals[i]
        target_val = sorted_vals[i]

        #permutation = [i]

        while start_val != target_val:
            #ni = 0
            #while not (available[ni] and original_vals[ni]==target_val): ni+=1
            ni = np.where((original_vals==target_val) & available)[0][0]
            available[ni] = False
            target_val = sorted_vals[ni]
            #permutation.append(ni)
            swaps += 1

        available[i] = False
        #permutations.append(permutation)
        
    return swaps#, permutations

In [271]:
 min_swaps(nparr)

9992

In [273]:
%%cython
import numpy as np
def min_swaps(sequence):
    original_vals = sequence
    sorted_vals = np.sort(original_vals)
    
    available = original_vals!=sorted_vals

    #permutations = []
    #cdef int i, ni, start_val, target_val, swaps = 0
    swaps = 0
    for i in range(original_vals.shape[0]):

        if not available[i]: continue

        start_val = original_vals[i]
        target_val = sorted_vals[i]

        #permutation = [i]

        while start_val != target_val:
            #ni = 0
            #while not (available[ni] and original_vals[ni]==target_val): ni+=1
            ni = np.where((original_vals==target_val) & available)[0][0]
            available[ni] = False
            target_val = sorted_vals[ni]
            #permutation.append(ni)
            swaps += 1

        available[i] = False
        #permutations.append(permutation)
        
    return swaps#, permutations

In [274]:
%timeit min_swaps(nparr)

77.4 ms ± 2.03 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [88]:
%timeit sorted(arr)
%timeit sorted(nparr)
%timeit np.sort(arr)
%timeit np.sort(nparr)
%timeit np.sort(nparr, kind='mergesort')
%timeit np.sort(nparr, kind='heapsort')
%timeit np.sort(nparr, kind='stable')

621 ns ± 3.49 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
6.03 µs ± 65.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
4.46 µs ± 227 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
1.68 µs ± 30 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
1.7 µs ± 20.3 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
1.77 µs ± 33.5 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
1.68 µs ± 6.05 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [87]:
np.sort?

In [59]:
a = r>0
a[[1,]] = False;a

array([ True, False,  True,  True,  True,  True,  True])

In [60]:
np.where((r==2) & a)

(array([2, 3]),)

In [58]:
np.where?

In [15]:
np.where(a[[1,2,3]]==2)

(array([1]),)

In [289]:
ov = original_vals[:7]
print(ov)
sov = sorted(ov)
print(sov)
av = [1 if ov[i]!=sov[i] else 0 for i in range(len(ov))]
print(av)

[3, 2, 2, 2, 4, 3, 2]
[2, 2, 2, 2, 3, 3, 4]
[1, 0, 0, 0, 1, 0, 1]


In [295]:
x = sorted(zip(ov, range(len(ov))))
x = list((v, oi, si) for si, (v, oi) in enumerate(x))
x

[(2, 1, 0), (2, 2, 1), (2, 3, 2), (2, 6, 3), (3, 0, 4), (3, 5, 5), (4, 4, 6)]

In [301]:
{
    k:[(oi, si) for _, oi, si in g if av[oi]]
    for k,g in it.groupby(x, key=operator.itemgetter(0))
}

{2: [(6, 3)], 3: [(0, 4)], 4: [(4, 6)]}

In [320]:
value_getter = operator.itemgetter(1)
x = sorted(enumerate(ov), key=value_getter)
{
    k:iter([idx for idx, _ in g if ov[idx]!=value_getter(x[idx])])
    for k, g in it.groupby(x, key=value_getter)
}

{2: <list_iterator at 0x7f3f29c95da0>,
 3: <list_iterator at 0x7f3f29c95160>,
 4: <list_iterator at 0x7f3f2aa1a9e8>}

In [456]:
%%cython
import itertools as it
import operator
from collections import deque
def min_swaps(sequence):
    original_vals = sequence
    length = len(original_vals)
    value_getter = operator.itemgetter(1)
    sorted_idcs_vals = sorted(enumerate(original_vals), key=value_getter)
    #print(f'ov: {original_vals}\nsiv: {sorted_idcs_vals}')
    available = [original_vals[idx]!=sorted_idcs_vals[idx][1] for idx in range(length)]
    val_to_idx = {
        k:iter(list(
            idx for idx, _ in g
            if available[idx]
            #if original_vals[idx]!=sorted_idcs_vals[idx][1]
        ))
        for k, g in it.groupby(sorted_idcs_vals, key=value_getter)
    }
    
    

    #permutations = []
    swaps = 0
    for i in range(length):

        if not available[i]: continue

        start_val = original_vals[i]
        target_val = sorted_idcs_vals[i][1]

        #permutation = [i]

        while start_val != target_val:
            ni = next(val_to_idx[target_val])
            #ni = val_to_idx[target_val].popleft()
            available[ni] = False
            target_val = sorted_idcs_vals[ni][1]
            #permutation.append(ni)
            swaps += 1

        
        next(val_to_idx[target_val])
        available[i] = False
        #permutations.append(permutation)
        
    return swaps#, permutations

In [459]:
%timeit min_swaps(arr)

13.1 ms ± 80.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [449]:
a = original_vals[:20]
print(a)
min_swaps(a)

[3, 2, 2, 2, 4, 3, 2, 1, 6, 5, 7, 4, 6, 6, 5, 4, 8, 4, 4, 1]


11

In [421]:
original_vals

[3,
 2,
 2,
 2,
 4,
 3,
 2,
 1,
 6,
 5,
 7,
 4,
 6,
 6,
 5,
 4,
 8,
 4,
 4,
 1,
 1,
 3,
 2,
 2,
 2,
 2,
 6,
 2,
 2,
 3,
 5,
 8,
 4,
 2,
 2]

In [365]:
z = list(range(1))

In [413]:
d = deque(z)
while d: d.popleft()

deque([])

In [367]:
%%timeit
d = list(z)
while d: d.pop(0)

241 ns ± 2.68 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [371]:
vg = operator.itemgetter(1)
lb = lambda x: x[1]

In [372]:
t = (1,2)
%timeit vg(t)
%timeit lb(t)
%timeit t[1]

67.7 ns ± 1.43 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
75.4 ns ± 0.447 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
31 ns ± 0.269 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [363]:
d = deque(range(5))
l = list(range(5))

In [364]:
%timeit d[0]
%timeit l[0]

29.9 ns ± 0.904 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
27.4 ns ± 0.167 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [599]:
%%cython
cpdef int ss(list a):
    cdef int swaps = 0
    cdef int n = len(a)
    cdef int i, j, iMin, temp
    for j in range(n-1):
        iMin = j
        for i in range(j+1, n):
            if (a[i] < a[iMin]):
                iMin = i
        if iMin != j:
            a[iMin] = a[j]
            swaps += 1
    return swaps

In [586]:
%%cython
import numpy as np
cimport numpy as np
cpdef int min_swapss(np.ndarray[np.int_t, ndim=1] a, int n):
    cdef int swaps = 0
    cdef int i, min_i
    for i in range(n-1):
        min_i = np.argmin(a[i:])
        if min_i != i:
            a[min_i] = a[i]
            swaps += 1
    return swaps

In [512]:
ov = [3, 2, 1]

In [513]:
%%timeit
min_swaps(ov)

2.77 µs ± 62.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [514]:
%%timeit
z = np.array(ov)
ss(z, len(ov))

4.63 µs ± 51.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [486]:
%%timeit
z = np.array(arr)

549 µs ± 5.55 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [487]:
%%timeit
len(arr)

62.7 ns ± 0.6 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [491]:
np.argmin?

[3, 2, 2, 2, 4, 3, 2]

In [505]:
deque([i for i in []])

deque([])

In [516]:
from collections import deque
from operator import itemgetter
from itertools import groupby

def min_swaps(sequence):
    """
    Returns miminum number of transpositions/swaps to sort given sequence.

    Much faster than a modified (even Cython-optimized) implementation
    of selection sort, even for short arrays.
    
    This is based on the finding disjoint permutation cycles between
    the sequence and its sorted order. It takes exactly length(cycle)-1
    transpositions to reverse a cycle.
    """

    # do lexical sort on (value, original_index) pairs
    # however sort is stable, so following is an option too (pairs are (original_index, value))
    value_getter = itemgetter(1)
    sorted_idcs_vals = sorted(enumerate(sequence), key=value_getter)
    # get relevant indices for every value
    val_to_idcs = {
        value:deque(
            idx for idx, _ in indices
            # if element is not stationary
            if sequence[idx]!=sorted_idcs_vals[idx][1]
        )
        for value, indices in groupby(sorted_idcs_vals, key=value_getter)
    }
    
    # The permutaion cycles can be built by uncommenting lines with "cycle(s)" 
    # I keep it here - it clarifies the algorithm and might be useful some other day
    #cycles = []
    swaps = 0
    while val_to_idcs:
        start_value, indices = next(iter(val_to_idcs.items()))

        # we have seen the element(s) already or it was stationary
        if not indices:
            del val_to_idcs[start_value]
            continue

        idx = indices.popleft()
        next_value = sorted_idcs_vals[idx][1]

        #cycle = [idx]
        while start_value != next_value:
            next_idx = val_to_idcs[next_value].popleft()
            next_value = sorted_idcs_vals[next_idx][1]
            #cycle.append(next_idx)
            swaps += 1

        #cycles.append(cycle)
        
    return swaps #, cycles

In [519]:
%timeit min_swaps(arr)

57.9 ms ± 885 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [617]:
def min_swaps(sequence):
    """
    Returns miminum number of transpositions/swaps to sort given sequence.

    Much faster than a modified (even Cython-optimized) implementation
    of selection sort, even for short arrays.
    
    This is based on the finding disjoint permutation cycles between
    the sequence and its sorted order. It takes exactly length(cycle)-1
    transpositions to reverse a cycle.
    """

    # do lexical sort on (value, original_index) pairs
    # however sort is stable, so following is an option too (pairs are (original_index, value))
    value_getter = itemgetter(1)
    sorted_idcs_vals = sorted(enumerate(sequence), key=value_getter)
    # get relevant indices for every value
    val_to_idcs = {
        value:deque(
            idx for idx, _ in indices
            # if element is not stationary
            if sequence[idx]!=sorted_idcs_vals[idx][1]
        )
        for value, indices in groupby(sorted_idcs_vals, key=value_getter)
    }
    
    # The permutaion cycles can be built by uncommenting lines with "cycle(s)" 
    # I keep it here - it clarifies the algorithm and might be useful some other day
    cycles = []
    swaps = 0
    for start_value in sequence:
        indices = val_to_idcs[start_value]

        # we have seen the element(s) already or it was stationary
        if not indices: continue

        idx = indices.popleft()
        next_value = sorted_idcs_vals[idx][1]

        cycle = [idx]
        while start_value != next_value:
            next_idx = val_to_idcs[next_value].popleft()
            next_value = sorted_idcs_vals[next_idx][1]
            cycle.append(next_idx)
            swaps += 1

        cycles.append(cycle)
        
    return swaps , cycles

In [570]:
%timeit min_swaps(arr)

18.4 ms ± 280 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [665]:
def min_swapz(sequence):
    original_vals = sequence
    length = len(original_vals)
    value_getter = operator.itemgetter(1)
    sorted_idcs_vals = sorted(enumerate(original_vals), key=value_getter)
    #print(f'ov: {original_vals}\nsiv: {sorted_idcs_vals}')
    available = [original_vals[idx]!=sorted_idcs_vals[idx][1] for idx in range(length)]
    val_to_idx = {
        k:iter(list(
            idx for idx, _ in g
            if available[idx]
            #if original_vals[idx]!=sorted_idcs_vals[idx][1]
        ))
        for k, g in it.groupby(sorted_idcs_vals, key=value_getter)
    }
    
    

    swaps = 0
    while any(available):
        i = np.random.randint(length)

        if not available[i]: continue

        start_val = original_vals[i]
        target_val = sorted_idcs_vals[i][1]


        while start_val != target_val:
            ni = next(val_to_idx[target_val])
            #ni = val_to_idx[target_val].popleft()
            #ni = val_to_idx[target_val].pop(0)
            available[ni] = False
            target_val = sorted_idcs_vals[ni][1]
            swaps += 1

        next(val_to_idx[target_val])
        available[i] = False
        
    return swaps

In [ ]:
%timeit min_swaps(arr)

In [549]:
%timeit sorted(arr)

3.17 ms ± 45 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [532]:
next(i, 8)

8

In [571]:
def minSwaps(arr): 
    n = len(arr) 
      
    # Create two arrays and use  
    # as pairs where first array  
    # is element and second array 
    # is position of first element 
    arrpos = [*enumerate(arr)] 
      
    # Sort the array by array element  
    # values to get right position of  
    # every element as the elements  
    # of second array. 
    arrpos.sort(key = lambda it:it[1]) 
      
    # To keep track of visited elements.  
    # Initialize all elements as not  
    # visited or false. 
    vis = {k:False for k in range(n)} 
      
    # Initialize result 
    ans = 0
    for i in range(n): 
          
        # alreadt swapped or  
        # alreadt present at  
        # correct position 
        if vis[i] or arrpos[i][0] == i: 
            continue
              
        # find number of nodes  
        # in this cycle and 
        # add it to ans 
        cycle_size = 0
        j = i 
        while not vis[j]: 
              
            # mark node as visited 
            vis[j] = True
              
            # move to next node 
            j = arrpos[j][0] 
            cycle_size += 1
              
        # update answer by adding 
        # current cycle 
        if cycle_size > 0: 
            ans += (cycle_size - 1) 
    # return answer 
    return ans 

In [697]:
def cycle_decomposition(permutation):
    """Generate cycles in the cyclic decomposition of a permutation.

        >>> list(cycle_decomposition([7, 2, 9, 5, 0, 3, 6, 8, 1, 4]))
        [[0, 7, 8, 1, 2, 9, 4], [3, 5], [6]]

    """
    unvisited = set(permutation)
    while unvisited:
        j = i = unvisited.pop()
        cycle = [i]
        while True:
            j = permutation[j]
            if j == i:
                break
            cycle.append(j)
            unvisited.remove(j)
        yield cycle

def minimum_swaps(seq):
    """Return minimum swaps needed to sort the sequence.

        >>> minimum_swaps([])
        0
        >>> minimum_swaps([2, 1])
        1
        >>> minimum_swaps([4, 8, 1, 5, 9, 3, 6, 0, 7, 2])
        7

    """
    permutation = sorted(range(len(seq)), key=seq.__getitem__)
    return sum(len(cycle) - 1 for cycle in cycle_decomposition(permutation))

In [592]:
l, p = min_swaps(original_vals); l

26

In [594]:
p

[[0, 7, 1, 19, 4, 2, 20, 11, 22, 15],
 [23, 17, 5],
 [24, 18, 21, 32, 10],
 [25, 9],
 [29, 8, 27, 14, 28, 12, 33, 16],
 [34, 31, 13],
 [26, 30]]

In [597]:
for z in p: print(np.array(original_vals)[z])

[3 1 2 1 4 2 1 4 2 4]
[2 4 3]
[2 4 3 4 7]
[2 5]
[3 6 2 5 2 6 2 8]
[2 8 6]
[6 5]


In [581]:
print(' '.join(map('{:2d}'.format, original_vals)))
print(' '.join(map('{:2d}'.format, sorted_vals)))
print(' '.join(map('{:2d}'.format, range(len(sorted_vals)))))

 3  2  2  2  4  3  2  1  6  5  7  4  6  6  5  4  8  4  4  1  1  3  2  2  2  2  6  2  2  3  5  8  4  2  2
 1  1  1  2  2  2  2  2  2  2  2  2  2  2  2  3  3  3  3  4  4  4  4  4  4  5  5  5  6  6  6  6  7  8  8
 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34


In [610]:
%%cython
cpdef int sslt(list a):
    cdef int swaps = 0
    cdef int n = len(a)
    cdef int i, j, iMin, temp
    for j in range(n-1):
        iMin = j
        for i in range(j+1, n):
            if (a[i] < a[iMin]):
                iMin = i
        if iMin != j:
            a[iMin] = a[j]
            swaps += 1
    return swaps

In [611]:
%%cython
cpdef int ssle(list a):
    cdef int swaps = 0
    cdef int n = len(a)
    cdef int i, j, iMin, temp
    for j in range(n-1):
        iMin = j
        for i in range(j+1, n):
            if (a[i] <= a[iMin]):
                iMin = i
        if iMin != j:
            a[iMin] = a[j]
            swaps += 1
    return swaps

In [601]:
min_swapss(np.array(original_vals), len(original_vals))

34

In [787]:
l = np.random.randint(0, 6, 50)
# np.random.shuffle(l)
print(f'{len(l)}:{l[:50]}')
print()
print(sslt(list(l)))
print(ssle(list(l)))
print()
print(min_swaps(l)[0])
print()
print(minimum_swaps(l))
print(minSwaps(l))
print()

m = 1e999
while True:
    z = min_swaps3(l)
    if z < m:
        m = z
        print(f'\r{m}', end='')

50:[0 5 5 2 2 2 2 5 4 2 5 5 3 2 4 0 2 1 2 2 4 0 2 3 3 2 1 5 2 5 0 1 5 0 5 0 5
 0 1 2 2 1 4 2 5 5 0 2 4 0]

36
49

33

46
46

24

KeyboardInterrupt: 

In [790]:
z = list(range(100000))
d=deque(z)
l=list(z)
%timeit [i for i in d]
%timeit [i for i in l]

2.15 ms ± 68.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
1.89 ms ± 16.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [772]:
%%cython
from collections import deque
from operator import itemgetter
from itertools import groupby
import numpy as np
cimport numpy as np
def min_swaps3(sequence):
    """
    Returns miminum number of transpositions/swaps to sort given sequence.

    Much faster than a modified (and even Cython-optimized) implementation
    of selection sort, even for short arrays.
    
    This is based on the finding disjoint permutation cycles between
    the sequence and its sorted order. It takes exactly length(cycle)-1
    transpositions to reverse a cycle.
    """

    # do lexical sort on (value, original_index) pairs
    # however sort is stable, so following is an option too (pairs are (original_index, value))
    value_getter = itemgetter(1)
    sorted_idcs_vals = sorted(enumerate(sequence), key=value_getter)
    # get relevant indices for every value
    val_to_idcs = {
        value:deque(
            idx for idx, _ in indices
            # if element is not stationary
            if sequence[idx]!=sorted_idcs_vals[idx][1]
        )
        for value, indices in groupby(sorted_idcs_vals, key=value_getter)
    }
    
    # The permutaion cycles can be built by uncommenting lines with "cycle(s)" 
    # I keep it here - it clarifies the algorithm and might be useful some other day
    #cycles = []
    swaps = 0
    ch = list(sequence)
    while ch:
        start_value = ch.pop(np.random.randint(len(ch)))
        indices = val_to_idcs[start_value]

        # we have seen the element(s) already or it was stationary
        if not indices: continue

        idx = indices.popleft()
        next_value = sorted_idcs_vals[idx][1]

        #cycle = [idx]
        while start_value != next_value:
            next_idx = val_to_idcs[next_value].popleft()
            next_value = sorted_idcs_vals[next_idx][1]
            #cycle.append(next_idx)
            swaps += 1

        #cycles.append(cycle)
        
    return swaps #, cycles